# Generated by Django 5.0.7 on 2024-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
