# Generated by Django 5.0.7 on 2024-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_role_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('seller', 'seller'), ('client', 'client')], default='client', max_length=50, null=True),
        ),
    ]
