# Generated by Django 5.0.7 on 2024-08-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='products',
            new_name='carts',
        ),
    ]
