# Generated by Django 5.0.7 on 2024-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='carts',
            field=models.ManyToManyField(to='sales.productsale'),
        ),
    ]
