# Generated by Django 5.0.7 on 2024-08-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.BooleanField(choices=[('waiting', 'waiting'), ('preparing', 'preparing'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='waiting'),
        ),
    ]
