# Generated by Django 5.0.7 on 2024-08-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_status'),
        ('sellers', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='sellers.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='carts',
            field=models.ManyToManyField(related_name='sales', to='sales.productsale'),
        ),
    ]
