# Generated by Django 5.0.7 on 2024-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_productsale_product_alter_sale_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller_id',
            field=models.IntegerField(default=0),
        ),
    ]
